title: Hiring for Tech
description: >
  The weekly newsletter for all things tech hiring. Tech interviews are hard, whether you're hiring or looking to be hired. Poor interview practices mean the right candidates are not being matched with the right companies. In this weekly newsletter, I'll send you advice on how to prepare for an interview, as a candidate or as an interviewer. Each edition is short, so you can read and be on your way.

author:
  name: Avik Das
  website: https://avikdas.com
  linkedin: https://linkedin.com/in/avikdas1990
  twitter: https://twitter.com/the_avik_das

linkedin-group: https://www.linkedin.com/groups/13938375/

plugins:
    - jekyll-feed
